<?php //Cargamos el doctype que tenemos configurado
    echo $this->doctype(); ?>
<html lang="es_ES">
    <head>
        <!--definimos la codificación de la página-->
        <?php
        echo $this->headMeta()->setCharset('utf8')?>
        <!--// definimos el título de la página-->
        <?php
        echo $this->headTitle($this->title)
        ?>
        <!--// aqui se definen los metas: keywords, autores, otros-->
        <?php //echo $this->headMeta()->appendName('keywords', 'framework, PHP, productivity');?>
        <?php //echo $this->headMeta()->setProperty('og:title', 'my article title');?>
        <?php //echo $this->headMeta()->setProperty('og:type', 'article');?>
        <!--// definimos las hojas de estilo-->
        <?php
        echo $this->headLink()->prependStylesheet($this->basePath().'/css/estilos.css')
        ?>
        <?php //echo $this->headStyle()?>
        <!--// definimos los ficheros javascript-->
        <?php
        echo $this->headScript()->prependFile($this->basePath().'/js/jquery.min.js')
        ?>
    </head>
    <body>
        <header>
            <h1>Encabezado</h1>
        </header>
        <div class="content">
        Saludo : <?php
        //Mostramos el parámetro pasado
        echo $this->saludo?>
        <?php
        //Aqui se muestra el contenido de la vista
        echo $this->content?>
        </div>
        <footer>&copy; Victor Robles</footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
