<?php
// module/Album/view/album/album/index.phtml

$title = 'Mi Album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">
        Agregar Nuevo Album
    </a>
</p>

<table class="table">
<tr>
    <th>Titulo</th>
    <th>Artista</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>    <td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));?>">Editar</a>
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));?>">Eliminar</a>
    </td>
</tr>
<?php endforeach; ?>
</table>